# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
    - repository: sls_install
      type: git
      name: CloudFabric-Internal/serverless-framework-install
    - repository: aws_bulk_tagger
      type: github
      name: rom1spi/aws-bulk-tagger
      endpoint: rom1spi

jobs:
- job: install_clone_deploy
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    - group: aws-creds-group
  steps:
    - template: install-serverless-framework.yml@sls_install
    - script: git clone https://github.com/rom1spi/aws-bulk-tagger
      displayName: Clone git repo
    - script: |
        export AWS_ACCESS_KEY_ID=$(AWS_ACCESS_KEY_ID)
        export AWS_SECRET_ACCESS_KEY=$(AWS_SECRET_ACCESS_KEY)
        sls config credentials --provider aws --key $(AWS_ACCESS_KEY_ID) --secret $(AWS_SECRET_ACCESS_KEY)
        cd aws-bulk-tagger
        sudo sls deploy -v
      displayName: Serverless deploy
