# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

resources:
  repositories:
    - repository: templates
      type: git
      name: CloudFabric-Internal/serverless-framework-install

jobs:
- template: install-serverless-framework.yml@templates  # Template reference
