# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
    - repository: sls_install
      type: git
      name: CloudFabric-Internal/serverless-framework-install
    - repository: aws_bulk_tagger
      type: github
      name: rom1spi/aws-bulk-tagger
      endpoint: rom1spi

jobs:
- template: install-serverless-framework.yml@sls_install
- template: serverless.yml@aws_bulk_tagger
