# Welcome to Serverless!
#
# Author: Romain Spinelli
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: aws-bulk-tagger
# app and org for use with dashboard.serverless.com
app: aws-bulk-tagger
org: <YOUR_ORG>

plugins:
  # https://serverless.com/plugins/serverless-pseudo-parameters/
  - serverless-pseudo-parameters

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

custom:
    defaultRegion: eu-west-3
    defaultStage: dev
    notifierTopicName: ${self:service}-notifier-${self:provider.stage}
    notifierTopicArn: { "Fn::Join" : ["", ["arn:aws:sns:${self:provider.region}:", { "Ref" : "AWS::AccountId" }, ":${self:custom.notifierTopicName}" ] ]  }

provider:
  name: aws
  runtime: python3.8
  memorySize: 128 

# you can overwrite defaults here
  stage: ${opt:stage, self:custom.defaultStage}
  region: ${opt:region, self:custom.defaultRegion}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - tag:GetResources
        - tag:TagResources
        - tag:UntagResources
        - tag:GetTagKeys
        - tag:GetTagValues
        - ec2:CreateTags
        - ec2:DeleteTags
      Resource: "*"         
    - Effect: "Allow"
      Action: "SNS:Publish"
      Resource:
        Ref: SNSNotifier

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  include:
#    - include-me.py
#    - include-me-dir/**
#  exclude:
#    - exclude-me.py
#    - exclude-me-dir/**

functions:
  bulk_tagger:
    handler: handler.bulk_tagger
#   Define function environment variables here
    environment:
      NOTIFIER_TOPIC_ARN: ${self:custom.notifierTopicArn}

# you can add CloudFormation resource templates here
resources:
  Resources:
    SNSNotifier:
      Type: AWS::SNS::Topic
      Properties: 
        DisplayName: "[${self:service}] News from ${opt:region, self:custom.defaultRegion}"
        TopicName: ${self:custom.notifierTopicName}
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"